default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: [ "--fix"]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: '24.1.0'
    hooks:
      - id: black
        language_version: python3.12
